#ifndef PIXEL_CLIENT_CONSTS
#define PIXEL_CLIENT_CONSTS

#define OP_HOME 1
#define OP_HOME_ALL 2
#define OP_CLEAR_ERROR_CODE 3
#define OP_SET_LIMIT 4
#define OP_SET_STEPS 5
#define OP_ADD_STEPS 6
#define OP_SET_ANGLE 7
#define OP_ADD_ANGLE 8
#define OP_REQUEST_TYPE 9

#define REQUEST_PING 1
#define REQUEST_PIXELS 2
#define REQUEST_MOVING_COUNT 3
#define REQUEST_IS_MOVING 4
#define REQUEST_TARGET_STEPS 5
#define REQUEST_STEPS 6
#define REQUEST_TARGET_ANGLE 7
#define REQUEST_ANGLE 8
#define REQUEST_LIMIT 9
#define REQUEST_STATUS 10
#define REQUEST_ERROR_CODE 11

#define ERROR_NONE 0
#define ERROR_UNKNOWN 1
#define ERROR_REQUEST 100
#define ERROR_REQUEST_WRONG_NUMBER_OF_BYTES 101
#define ERROR_REQUEST_WRONG_TYPE 102
#define ERROR_REQUEST_WRONG_PIXEL 103
#define ERROR_READER 200
#define ERROR_READER_DATA_NOT_AVAILABLE 201
#define ERROR_READER_UNKNOWN_COMMAND 202
#define ERROR_READER_UNKNOWN_REQUEST 203
#define ERROR_WIRE 300
#define ERROR_WIRE_FAILED_TO_READ 302
#define ERROR_WIRE_FAILED_TO_WRITE 301
#define ERROR_WIRE_FAILED_TO_READ 302
#define ERROR_TRANSMISSION 400
#define ERROR_TRANSMISSION_LENGTH_TO_LONG_FOR_BUFFER 401
#define ERROR_TRANSMISSION_ADDRESS_SEND_NACK_RECEIVED 402
#define ERROR_TRANSMISSION_WIRE_DATA_SEND_NACK_RECEIVED 403
#define ERROR_TRANSMISSION_WIRE_OTHER_TWI_ERROR 404
#define ERROR_TRANSMISSION_WIRE_OTHER_TIMEOUT 405

#endif
