#ifndef PIXEL_CLIENT_CONSTS
#define PIXEL_CLIENT_CONSTS

#define OP_INIT 0
#define OP_HOME 1
#define OP_CLEAR_ERROR_CODE 2
#define OP_SET_LIMIT 3
#define OP_SET_STEPS 4
#define OP_ADD_STEPS 5
#define OP_SET_ANGLE 6
#define OP_ADD_ANGLE 7
#define OP_REQUEST_TYPE 8

#define REQUEST_PING 0
#define REQUEST_ERROR_CODE 1
#define REQUEST_MOVING_COUNT 2
#define REQUEST_STATUS 3

#endif
