#ifndef PIXEL_CLIENT_CONSTS
#define PIXEL_CLIENT_CONSTS

#define REQUEST_PING   0
#define REQUEST_ERROR  1

#define OP_HOME 0
#define OP_SET_LIMITS_AND_HOME 1
#define OP_SET_LIMITS 2
#define OP_SET_STEPS 3
#define OP_ADD_STEPS 4
#define OP_SET_ANGLE 5
#define OP_ADD_ANGLE 6
#define OP_REQUEST_TYPE 7

#endif
